Repository KIM-DONGJU/wc-lol, pull requests merged in 2024-09, with the labels that each got.

#16 [#12] 대전 생성 기능 추가 및 일부 편의성 개선
  .stylelintcache
  src/App.vue
  src/assets/images/error/cancel.svg
  src/assets/images/error/secure_data.svg
  src/components/CommonLoadingSpinner.vue
  src/components/CommonModal.vue
  src/components/CommonToastMessage.vue
  src/components/CreateMatchBottomSheet.vue
  src/components/CreateMatchGroupModal.vue
  src/components/DeleteMatchConfirmModal.vue
  src/components/DeleteMatchGroupConfirmModal.vue
  src/components/MatchGroupVictoryConfirmModal.vue
  src/components/SetPosition.vue
  src/components/TierTable.vue
  src/components/UpdateMatchBottomSheet.vue
  src/composables/usePosition.ts
  src/constants/position.ts
  src/layouts/AppNav.vue
  src/plugins/vuetify.ts
  src/router/index.ts
  src/stores/message.ts
  src/stores/useAuth.ts
  src/stores/useCommon.ts
  src/stores/useMatch.ts
  src/stores/useUsers.ts
  src/styles/_export.module.scss
  src/styles/_variables.scss
  src/views/CreateMatchView.vue
  src/views/MemberList.vue
  src/views/SignUpView.vue
  src/views/UserDetailView.vue
Labels: please review

#14 [#13] 롤 챔피언 페이지 기능 개발
  .stylelintcache
  package-lock.json
  package.json
  src/constants/champion.ts
  src/constants/routes.ts
  src/interfaces/champion.d.ts
  src/layouts/AppNav.vue
  src/router/index.ts
  src/stores/useChampion.ts
  src/views/ChampionList.vue
  src/views/LoginView.vue
  src/views/SignUpView.vue
  yarn.lock
Labels: refactoring, feature

#17 모스트 챔피언 선택 기능 구현
  .stylelintcache
  src/components/SelectMostChampions.vue
  src/components/TierTable.vue
  src/constants/routes.ts
  src/router/index.ts
  src/stores/useUsers.ts
  yarn.lock
Labels: feature
